version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
     ##Add the port in the firewall
    ports:
      - 1450:1433
    container_name: mssql
    environment:
      - MSSQL_SA_PASSWORD=Xandriaisalovelygirl4
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adenote
    env_file: example.env
    depends_on:
      - db
      - rabbitmq
    ports:
     - 8000:80

networks:
  default:
    driver: bridge

