version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
     ##Add the port in the firewall
    ports:
      - 1450:1433
    container_name: mssql
    environment:
      - MSSQL_SA_PASSWORD=Xandriaisalovelygirl4
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adenote
    env_file: .env
    depends_on:
      - db
    ports:
     - 8000:80

