var searchData=
[
  ['ibookrepository_116',['IBookRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IBookRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ibookrepository_2ecs_117',['IBookRepository.cs',['../IBookRepository_8cs.html',1,'']]],
  ['ibookservice_118',['IBookService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IBookService.html',1,'AdeNote::Infrastructure::Services']]],
  ['ibookservice_2ecs_119',['IBookService.cs',['../IBookService_8cs.html',1,'']]],
  ['id_120',['Id',['../classAdeNote_1_1Models_1_1DTOs_1_1LabelDTO.html#a29005f5091d9fecc55b7cba1e63a9679',1,'AdeNote.Models.DTOs.LabelDTO.Id()'],['../classAdeNote_1_1Models_1_1DTOs_1_1BookPages.html#a3086f89c5f8f0715506981391c3c03ab',1,'AdeNote.Models.DTOs.BookPages.Id()'],['../classAdeNote_1_1Models_1_1DTOs_1_1BookDTO.html#ae57c7eb3546d3d38541b284225ff6de0',1,'AdeNote.Models.DTOs.BookDTO.Id()'],['../classAdeNote_1_1Models_1_1BaseClass.html#a5e1dd744938a11239b5fcd7cd1d7443d',1,'AdeNote.Models.BaseClass.Id()']]],
  ['ilabelpagerepository_121',['ILabelPageRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelPageRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelpagerepository_2ecs_122',['ILabelPageRepository.cs',['../ILabelPageRepository_8cs.html',1,'']]],
  ['ilabelrepository_123',['ILabelRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelrepository_2ecs_124',['ILabelRepository.cs',['../ILabelRepository_8cs.html',1,'']]],
  ['ilabelservice_125',['ILabelService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ILabelService.html',1,'AdeNote::Infrastructure::Services']]],
  ['ilabelservice_2ecs_126',['ILabelService.cs',['../ILabelService_8cs.html',1,'']]],
  ['ipagerepository_127',['IPageRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IPageRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ipagerepository_2ecs_128',['IPageRepository.cs',['../IPageRepository_8cs.html',1,'']]],
  ['ipageservice_129',['IPageService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IPageService.html',1,'AdeNote::Infrastructure::Services']]],
  ['ipageservice_2ecs_130',['IPageService.cs',['../IPageService_8cs.html',1,'']]],
  ['irepository_131',['IRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_2ecs_132',['IRepository.cs',['../IRepository_8cs.html',1,'']]],
  ['irepository_3c_20book_20_3e_133',['IRepository&lt; Book &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20label_20_3e_134',['IRepository&lt; Label &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20page_20_3e_135',['IRepository&lt; Page &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iuseridentity_136',['IUserIdentity',['../interfaceAdeNote_1_1Infrastructure_1_1Utilities_1_1IUserIdentity.html',1,'AdeNote::Infrastructure::Utilities']]],
  ['iuseridentity_2ecs_137',['IUserIdentity.cs',['../IUserIdentity_8cs.html',1,'']]]
];
