var searchData=
[
  ['iauthservice_1337',['IAuthService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Authentication_1_1IAuthService.html',1,'AdeNote::Infrastructure::Services::Authentication']]],
  ['ibaseentity_1338',['IBaseEntity',['../interfaceAdeNote_1_1Models_1_1IBaseEntity.html',1,'AdeNote::Models']]],
  ['iblobservice_1339',['IBlobService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Blob_1_1IBlobService.html',1,'AdeNote::Infrastructure::Services::Blob']]],
  ['ibookrepository_1340',['IBookRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IBookRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ibookservice_1341',['IBookService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1BookSetting_1_1IBookService.html',1,'AdeNote::Infrastructure::Services::BookSetting']]],
  ['ichatservice_1342',['IChatService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ChatService_1_1IChatService.html',1,'AdeNote::Infrastructure::Services::ChatService']]],
  ['identitydbcontext_1343',['IdentityDbContext',['../classAdeNote_1_1Db_1_1IdentityDbContext.html',1,'AdeNote::Db']]],
  ['iemailservice_1344',['IEmailService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1EmailSettings_1_1IEmailService.html',1,'AdeNote::Infrastructure::Services::EmailSettings']]],
  ['iexcel_1345',['IExcel',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Excel_1_1IExcel.html',1,'AdeNote::Infrastructure::Services::Excel']]],
  ['iexportservice_1346',['IExportService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Export_1_1IExportService.html',1,'AdeNote::Infrastructure::Services::Export']]],
  ['ifileservice_1347',['IFileService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Blob_1_1IFileService.html',1,'AdeNote::Infrastructure::Services::Blob']]],
  ['ihangfireuserrepository_1348',['IHangfireUserRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IHangfireUserRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelpagerepository_1349',['ILabelPageRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelPageRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelrepository_1350',['ILabelRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelservice_1351',['ILabelService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1LabelSettings_1_1ILabelService.html',1,'AdeNote::Infrastructure::Services::LabelSettings']]],
  ['importbookdto_1352',['ImportBookDto',['../classAdeNote_1_1Models_1_1DTOs_1_1ImportBookDto.html',1,'AdeNote::Models::DTOs']]],
  ['importsheet_1353',['ImportSheet',['../classAdeNote_1_1Infrastructure_1_1Utilities_1_1ExcelSettings_1_1ImportSheet.html',1,'AdeNote::Infrastructure::Utilities::ExcelSettings']]],
  ['inotificationservice_1354',['INotificationService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Notification_1_1INotificationService.html',1,'AdeNote::Infrastructure::Services::Notification']]],
  ['insertvideodto_1355',['InsertVideoDto',['../classAdeNote_1_1Models_1_1DTOs_1_1InsertVideoDto.html',1,'AdeNote::Models::DTOs']]],
  ['insertvideorequest_1356',['InsertVideoRequest',['../classAdeNote_1_1Infrastructure_1_1Requests_1_1InsertVideo_1_1InsertVideoRequest.html',1,'AdeNote::Infrastructure::Requests::InsertVideo']]],
  ['insertvideorequesthandler_1357',['InsertVideoRequestHandler',['../classAdeNote_1_1Infrastructure_1_1Requests_1_1InsertVideo_1_1InsertVideoRequestHandler.html',1,'AdeNote::Infrastructure::Requests::InsertVideo']]],
  ['insertvideovalidator_1358',['InsertVideoValidator',['../classAdeNote_1_1Infrastructure_1_1Utilities_1_1Validations_1_1InsertVideoValidator.html',1,'AdeNote::Infrastructure::Utilities::Validations']]],
  ['ipagerepository_1359',['IPageRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IPageRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ipageservice_1360',['IPageService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1PageSettings_1_1IPageService.html',1,'AdeNote::Infrastructure::Services::PageSettings']]],
  ['irecoverycoderepository_1361',['IRecoveryCodeRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRecoveryCodeRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irefreshtokenrepository_1362',['IRefreshTokenRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRefreshTokenRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_1363',['IRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20book_20_3e_1364',['IRepository&lt; Book &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20hangfireuser_20_3e_1365',['IRepository&lt; HangfireUser &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20label_20_3e_1366',['IRepository&lt; Label &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20page_20_3e_1367',['IRepository&lt; Page &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20recoverycode_20_3e_1368',['IRepository&lt; RecoveryCode &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20refreshtoken_20_3e_1369',['IRepository&lt; RefreshToken &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20ticket_20_3e_1370',['IRepository&lt; Ticket &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20user_20_3e_1371',['IRepository&lt; User &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20video_20_3e_1372',['IRepository&lt; Video &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ismsservice_1373',['ISmsService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1SmsSettings_1_1ISmsService.html',1,'AdeNote::Infrastructure::Services::SmsSettings']]],
  ['istatisticsservice_1374',['IStatisticsService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Statistics_1_1IStatisticsService.html',1,'AdeNote::Infrastructure::Services::Statistics']]],
  ['itexttranslation_1375',['ITextTranslation',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1TranslationAI_1_1ITextTranslation.html',1,'AdeNote::Infrastructure::Services::TranslationAI']]],
  ['iticketrepository_1376',['ITicketRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ITicketRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iticketservice_1377',['ITicketService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1TicketSettings_1_1ITicketService.html',1,'AdeNote::Infrastructure::Services::TicketSettings']]],
  ['iuseridentity_1378',['IUserIdentity',['../interfaceAdeNote_1_1Infrastructure_1_1Utilities_1_1UserConfiguation_1_1IUserIdentity.html',1,'AdeNote::Infrastructure::Utilities::UserConfiguation']]],
  ['iuserrepository_1379',['IUserRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IUserRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iuserservice_1380',['IUserService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1UserSettings_1_1IUserService.html',1,'AdeNote::Infrastructure::Services::UserSettings']]],
  ['ivideorepository_1381',['IVideoRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IVideoRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iwordservice_1382',['IWordService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Word_1_1IWordService.html',1,'AdeNote::Infrastructure::Services::Word']]]
];
