var searchData=
[
  ['iauthservice_804',['IAuthService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IAuthService.html',1,'AdeNote::Infrastructure::Services']]],
  ['iblobservice_805',['IBlobService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IBlobService.html',1,'AdeNote::Infrastructure::Services']]],
  ['ibookrepository_806',['IBookRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IBookRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ibookservice_807',['IBookService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IBookService.html',1,'AdeNote::Infrastructure::Services']]],
  ['iemailservice_808',['IEmailService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IEmailService.html',1,'AdeNote::Infrastructure::Services']]],
  ['iexcel_809',['IExcel',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IExcel.html',1,'AdeNote::Infrastructure::Services']]],
  ['iexportservice_810',['IExportService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IExportService.html',1,'AdeNote::Infrastructure::Services']]],
  ['ifileservice_811',['IFileService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IFileService.html',1,'AdeNote::Infrastructure::Services']]],
  ['ihangfireuserrepository_812',['IHangfireUserRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IHangfireUserRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelpagerepository_813',['ILabelPageRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelPageRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelrepository_814',['ILabelRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelservice_815',['ILabelService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ILabelService.html',1,'AdeNote::Infrastructure::Services']]],
  ['importbookdto_816',['ImportBookDto',['../classAdeNote_1_1Models_1_1DTOs_1_1ImportBookDto.html',1,'AdeNote::Models::DTOs']]],
  ['importsheet_817',['ImportSheet',['../classAdeNote_1_1Infrastructure_1_1Utilities_1_1ImportSheet.html',1,'AdeNote::Infrastructure::Utilities']]],
  ['inotificationservice_818',['INotificationService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1INotificationService.html',1,'AdeNote::Infrastructure::Services']]],
  ['ipagerepository_819',['IPageRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IPageRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ipageservice_820',['IPageService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IPageService.html',1,'AdeNote::Infrastructure::Services']]],
  ['irecoverycoderepository_821',['IRecoveryCodeRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRecoveryCodeRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irefreshtokenrepository_822',['IRefreshTokenRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRefreshTokenRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_823',['IRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20book_20_3e_824',['IRepository&lt; Book &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20hangfireuser_20_3e_825',['IRepository&lt; HangfireUser &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20label_20_3e_826',['IRepository&lt; Label &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20page_20_3e_827',['IRepository&lt; Page &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20recoverycode_20_3e_828',['IRepository&lt; RecoveryCode &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20refreshtoken_20_3e_829',['IRepository&lt; RefreshToken &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20ticket_20_3e_830',['IRepository&lt; Ticket &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20user_20_3e_831',['IRepository&lt; User &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ismsservice_832',['ISmsService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ISmsService.html',1,'AdeNote::Infrastructure::Services']]],
  ['istatisticsservice_833',['IStatisticsService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IStatisticsService.html',1,'AdeNote::Infrastructure::Services']]],
  ['itexttranslation_834',['ITextTranslation',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ITextTranslation.html',1,'AdeNote::Infrastructure::Services']]],
  ['iticketrepository_835',['ITicketRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ITicketRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iticketservice_836',['ITicketService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ITicketService.html',1,'AdeNote::Infrastructure::Services']]],
  ['iuseridentity_837',['IUserIdentity',['../interfaceAdeNote_1_1Infrastructure_1_1Utilities_1_1IUserIdentity.html',1,'AdeNote::Infrastructure::Utilities']]],
  ['iuserrepository_838',['IUserRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IUserRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iuserservice_839',['IUserService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IUserService.html',1,'AdeNote::Infrastructure::Services']]],
  ['ivalidatorservice_840',['IValidatorService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IValidatorService.html',1,'AdeNote::Infrastructure::Services']]],
  ['iwordservice_841',['IWordService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IWordService.html',1,'AdeNote::Infrastructure::Services']]]
];
