var searchData=
[
  ['iauthservice_1205',['IAuthService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Authentication_1_1IAuthService.html',1,'AdeNote::Infrastructure::Services::Authentication']]],
  ['ibaseentity_1206',['IBaseEntity',['../interfaceAdeNote_1_1Models_1_1IBaseEntity.html',1,'AdeNote::Models']]],
  ['iblobservice_1207',['IBlobService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Blob_1_1IBlobService.html',1,'AdeNote::Infrastructure::Services::Blob']]],
  ['ibookrepository_1208',['IBookRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IBookRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ibookservice_1209',['IBookService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1BookSetting_1_1IBookService.html',1,'AdeNote::Infrastructure::Services::BookSetting']]],
  ['identitydbcontext_1210',['IdentityDbContext',['../classAdeNote_1_1Db_1_1IdentityDbContext.html',1,'AdeNote::Db']]],
  ['iemailservice_1211',['IEmailService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1EmailSettings_1_1IEmailService.html',1,'AdeNote::Infrastructure::Services::EmailSettings']]],
  ['iexcel_1212',['IExcel',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Excel_1_1IExcel.html',1,'AdeNote::Infrastructure::Services::Excel']]],
  ['iexportservice_1213',['IExportService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Export_1_1IExportService.html',1,'AdeNote::Infrastructure::Services::Export']]],
  ['ifileservice_1214',['IFileService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Blob_1_1IFileService.html',1,'AdeNote::Infrastructure::Services::Blob']]],
  ['ihangfireuserrepository_1215',['IHangfireUserRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IHangfireUserRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelpagerepository_1216',['ILabelPageRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelPageRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelrepository_1217',['ILabelRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelservice_1218',['ILabelService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1LabelSettings_1_1ILabelService.html',1,'AdeNote::Infrastructure::Services::LabelSettings']]],
  ['importbookdto_1219',['ImportBookDto',['../classAdeNote_1_1Models_1_1DTOs_1_1ImportBookDto.html',1,'AdeNote::Models::DTOs']]],
  ['importsheet_1220',['ImportSheet',['../classAdeNote_1_1Infrastructure_1_1Utilities_1_1ExcelSettings_1_1ImportSheet.html',1,'AdeNote::Infrastructure::Utilities::ExcelSettings']]],
  ['inotificationservice_1221',['INotificationService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Notification_1_1INotificationService.html',1,'AdeNote::Infrastructure::Services::Notification']]],
  ['ipagerepository_1222',['IPageRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IPageRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ipageservice_1223',['IPageService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1PageSettings_1_1IPageService.html',1,'AdeNote::Infrastructure::Services::PageSettings']]],
  ['irecoverycoderepository_1224',['IRecoveryCodeRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRecoveryCodeRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irefreshtokenrepository_1225',['IRefreshTokenRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRefreshTokenRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_1226',['IRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20book_20_3e_1227',['IRepository&lt; Book &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20hangfireuser_20_3e_1228',['IRepository&lt; HangfireUser &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20label_20_3e_1229',['IRepository&lt; Label &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20page_20_3e_1230',['IRepository&lt; Page &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20recoverycode_20_3e_1231',['IRepository&lt; RecoveryCode &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20refreshtoken_20_3e_1232',['IRepository&lt; RefreshToken &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20ticket_20_3e_1233',['IRepository&lt; Ticket &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20user_20_3e_1234',['IRepository&lt; User &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ismsservice_1235',['ISmsService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1SmsSettings_1_1ISmsService.html',1,'AdeNote::Infrastructure::Services::SmsSettings']]],
  ['istatisticsservice_1236',['IStatisticsService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Statistics_1_1IStatisticsService.html',1,'AdeNote::Infrastructure::Services::Statistics']]],
  ['itexttranslation_1237',['ITextTranslation',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1TranslationAI_1_1ITextTranslation.html',1,'AdeNote::Infrastructure::Services::TranslationAI']]],
  ['iticketrepository_1238',['ITicketRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ITicketRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iticketservice_1239',['ITicketService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1TicketSettings_1_1ITicketService.html',1,'AdeNote::Infrastructure::Services::TicketSettings']]],
  ['iuseridentity_1240',['IUserIdentity',['../interfaceAdeNote_1_1Infrastructure_1_1Utilities_1_1UserConfiguation_1_1IUserIdentity.html',1,'AdeNote::Infrastructure::Utilities::UserConfiguation']]],
  ['iuserrepository_1241',['IUserRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IUserRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iuserservice_1242',['IUserService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1UserSettings_1_1IUserService.html',1,'AdeNote::Infrastructure::Services::UserSettings']]],
  ['iwordservice_1243',['IWordService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Word_1_1IWordService.html',1,'AdeNote::Infrastructure::Services::Word']]]
];
