var searchData=
[
  ['iauthservice_763',['IAuthService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IAuthService.html',1,'AdeNote::Infrastructure::Services']]],
  ['iblobservice_764',['IBlobService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IBlobService.html',1,'AdeNote::Infrastructure::Services']]],
  ['ibookrepository_765',['IBookRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IBookRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ibookservice_766',['IBookService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IBookService.html',1,'AdeNote::Infrastructure::Services']]],
  ['iemailservice_767',['IEmailService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IEmailService.html',1,'AdeNote::Infrastructure::Services']]],
  ['iexcel_768',['IExcel',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IExcel.html',1,'AdeNote::Infrastructure::Services']]],
  ['iexportservice_769',['IExportService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IExportService.html',1,'AdeNote::Infrastructure::Services']]],
  ['ifileservice_770',['IFileService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IFileService.html',1,'AdeNote::Infrastructure::Services']]],
  ['ihangfireuserrepository_771',['IHangfireUserRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IHangfireUserRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelpagerepository_772',['ILabelPageRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelPageRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelrepository_773',['ILabelRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelservice_774',['ILabelService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ILabelService.html',1,'AdeNote::Infrastructure::Services']]],
  ['importbookdto_775',['ImportBookDto',['../classAdeNote_1_1Models_1_1DTOs_1_1ImportBookDto.html',1,'AdeNote::Models::DTOs']]],
  ['importsheet_776',['ImportSheet',['../classAdeNote_1_1Infrastructure_1_1Utilities_1_1ImportSheet.html',1,'AdeNote::Infrastructure::Utilities']]],
  ['inotificationservice_777',['INotificationService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1INotificationService.html',1,'AdeNote::Infrastructure::Services']]],
  ['ipagerepository_778',['IPageRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IPageRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ipageservice_779',['IPageService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IPageService.html',1,'AdeNote::Infrastructure::Services']]],
  ['irecoverycoderepository_780',['IRecoveryCodeRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRecoveryCodeRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irefreshtokenrepository_781',['IRefreshTokenRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRefreshTokenRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_782',['IRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20book_20_3e_783',['IRepository&lt; Book &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20hangfireuser_20_3e_784',['IRepository&lt; HangfireUser &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20label_20_3e_785',['IRepository&lt; Label &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20page_20_3e_786',['IRepository&lt; Page &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20recoverycode_20_3e_787',['IRepository&lt; RecoveryCode &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20refreshtoken_20_3e_788',['IRepository&lt; RefreshToken &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20ticket_20_3e_789',['IRepository&lt; Ticket &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20user_20_3e_790',['IRepository&lt; User &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ismsservice_791',['ISmsService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ISmsService.html',1,'AdeNote::Infrastructure::Services']]],
  ['istatisticsservice_792',['IStatisticsService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IStatisticsService.html',1,'AdeNote::Infrastructure::Services']]],
  ['itexttranslation_793',['ITextTranslation',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ITextTranslation.html',1,'AdeNote::Infrastructure::Services']]],
  ['iticketrepository_794',['ITicketRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ITicketRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iticketservice_795',['ITicketService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ITicketService.html',1,'AdeNote::Infrastructure::Services']]],
  ['iuseridentity_796',['IUserIdentity',['../interfaceAdeNote_1_1Infrastructure_1_1Utilities_1_1IUserIdentity.html',1,'AdeNote::Infrastructure::Utilities']]],
  ['iuserrepository_797',['IUserRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IUserRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iuserservice_798',['IUserService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IUserService.html',1,'AdeNote::Infrastructure::Services']]],
  ['iwordservice_799',['IWordService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IWordService.html',1,'AdeNote::Infrastructure::Services']]]
];
