var searchData=
[
  ['iauthservice_1311',['IAuthService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Authentication_1_1IAuthService.html',1,'AdeNote::Infrastructure::Services::Authentication']]],
  ['ibaseentity_1312',['IBaseEntity',['../interfaceAdeNote_1_1Models_1_1IBaseEntity.html',1,'AdeNote::Models']]],
  ['iblobservice_1313',['IBlobService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Blob_1_1IBlobService.html',1,'AdeNote::Infrastructure::Services::Blob']]],
  ['ibookrepository_1314',['IBookRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IBookRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ibookservice_1315',['IBookService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1BookSetting_1_1IBookService.html',1,'AdeNote::Infrastructure::Services::BookSetting']]],
  ['ichatservice_1316',['IChatService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ChatService_1_1IChatService.html',1,'AdeNote::Infrastructure::Services::ChatService']]],
  ['identitydbcontext_1317',['IdentityDbContext',['../classAdeNote_1_1Db_1_1IdentityDbContext.html',1,'AdeNote::Db']]],
  ['iemailservice_1318',['IEmailService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1EmailSettings_1_1IEmailService.html',1,'AdeNote::Infrastructure::Services::EmailSettings']]],
  ['iexcel_1319',['IExcel',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Excel_1_1IExcel.html',1,'AdeNote::Infrastructure::Services::Excel']]],
  ['iexportservice_1320',['IExportService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Export_1_1IExportService.html',1,'AdeNote::Infrastructure::Services::Export']]],
  ['ifileservice_1321',['IFileService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Blob_1_1IFileService.html',1,'AdeNote::Infrastructure::Services::Blob']]],
  ['ihangfireuserrepository_1322',['IHangfireUserRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IHangfireUserRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelpagerepository_1323',['ILabelPageRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelPageRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelrepository_1324',['ILabelRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ilabelservice_1325',['ILabelService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1LabelSettings_1_1ILabelService.html',1,'AdeNote::Infrastructure::Services::LabelSettings']]],
  ['importbookdto_1326',['ImportBookDto',['../classAdeNote_1_1Models_1_1DTOs_1_1ImportBookDto.html',1,'AdeNote::Models::DTOs']]],
  ['importsheet_1327',['ImportSheet',['../classAdeNote_1_1Infrastructure_1_1Utilities_1_1ExcelSettings_1_1ImportSheet.html',1,'AdeNote::Infrastructure::Utilities::ExcelSettings']]],
  ['inotificationservice_1328',['INotificationService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Notification_1_1INotificationService.html',1,'AdeNote::Infrastructure::Services::Notification']]],
  ['insertvideodto_1329',['InsertVideoDto',['../classAdeNote_1_1Models_1_1DTOs_1_1InsertVideoDto.html',1,'AdeNote::Models::DTOs']]],
  ['insertvideorequest_1330',['InsertVideoRequest',['../classAdeNote_1_1Infrastructure_1_1Requests_1_1InsertVideo_1_1InsertVideoRequest.html',1,'AdeNote::Infrastructure::Requests::InsertVideo']]],
  ['insertvideorequesthandler_1331',['InsertVideoRequestHandler',['../classAdeNote_1_1Infrastructure_1_1Requests_1_1InsertVideo_1_1InsertVideoRequestHandler.html',1,'AdeNote::Infrastructure::Requests::InsertVideo']]],
  ['insertvideovalidator_1332',['InsertVideoValidator',['../classAdeNote_1_1Infrastructure_1_1Utilities_1_1Validations_1_1InsertVideoValidator.html',1,'AdeNote::Infrastructure::Utilities::Validations']]],
  ['ipagerepository_1333',['IPageRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IPageRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ipageservice_1334',['IPageService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1PageSettings_1_1IPageService.html',1,'AdeNote::Infrastructure::Services::PageSettings']]],
  ['irecoverycoderepository_1335',['IRecoveryCodeRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRecoveryCodeRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irefreshtokenrepository_1336',['IRefreshTokenRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRefreshTokenRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_1337',['IRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20book_20_3e_1338',['IRepository&lt; Book &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20hangfireuser_20_3e_1339',['IRepository&lt; HangfireUser &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20label_20_3e_1340',['IRepository&lt; Label &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20page_20_3e_1341',['IRepository&lt; Page &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20recoverycode_20_3e_1342',['IRepository&lt; RecoveryCode &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20refreshtoken_20_3e_1343',['IRepository&lt; RefreshToken &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20ticket_20_3e_1344',['IRepository&lt; Ticket &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20user_20_3e_1345',['IRepository&lt; User &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['irepository_3c_20video_20_3e_1346',['IRepository&lt; Video &gt;',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['ismsservice_1347',['ISmsService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1SmsSettings_1_1ISmsService.html',1,'AdeNote::Infrastructure::Services::SmsSettings']]],
  ['istatisticsservice_1348',['IStatisticsService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Statistics_1_1IStatisticsService.html',1,'AdeNote::Infrastructure::Services::Statistics']]],
  ['itexttranslation_1349',['ITextTranslation',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1TranslationAI_1_1ITextTranslation.html',1,'AdeNote::Infrastructure::Services::TranslationAI']]],
  ['iticketrepository_1350',['ITicketRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ITicketRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iticketservice_1351',['ITicketService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1TicketSettings_1_1ITicketService.html',1,'AdeNote::Infrastructure::Services::TicketSettings']]],
  ['iuseridentity_1352',['IUserIdentity',['../interfaceAdeNote_1_1Infrastructure_1_1Utilities_1_1UserConfiguation_1_1IUserIdentity.html',1,'AdeNote::Infrastructure::Utilities::UserConfiguation']]],
  ['iuserrepository_1353',['IUserRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IUserRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iuserservice_1354',['IUserService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1UserSettings_1_1IUserService.html',1,'AdeNote::Infrastructure::Services::UserSettings']]],
  ['ivideorepository_1355',['IVideoRepository',['../interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IVideoRepository.html',1,'AdeNote::Infrastructure::Repository']]],
  ['iwordservice_1356',['IWordService',['../interfaceAdeNote_1_1Infrastructure_1_1Services_1_1Word_1_1IWordService.html',1,'AdeNote::Infrastructure::Services::Word']]]
];
