var annotated_dup =
[
    [ "AdeNote", "namespaceAdeNote.html", [
      [ "Controllers", "namespaceAdeNote_1_1Controllers.html", [
        [ "AuthenticationController", "classAdeNote_1_1Controllers_1_1AuthenticationController.html", "classAdeNote_1_1Controllers_1_1AuthenticationController" ],
        [ "BaseController", "classAdeNote_1_1Controllers_1_1BaseController.html", "classAdeNote_1_1Controllers_1_1BaseController" ],
        [ "BookController", "classAdeNote_1_1Controllers_1_1BookController.html", "classAdeNote_1_1Controllers_1_1BookController" ],
        [ "DashboardController", "classAdeNote_1_1Controllers_1_1DashboardController.html", "classAdeNote_1_1Controllers_1_1DashboardController" ],
        [ "LabelController", "classAdeNote_1_1Controllers_1_1LabelController.html", "classAdeNote_1_1Controllers_1_1LabelController" ],
        [ "PageController", "classAdeNote_1_1Controllers_1_1PageController.html", "classAdeNote_1_1Controllers_1_1PageController" ],
        [ "TicketController", "classAdeNote_1_1Controllers_1_1TicketController.html", "classAdeNote_1_1Controllers_1_1TicketController" ],
        [ "UserController", "classAdeNote_1_1Controllers_1_1UserController.html", "classAdeNote_1_1Controllers_1_1UserController" ]
      ] ],
      [ "Db", "namespaceAdeNote_1_1Db.html", [
        [ "NoteDbContext", "classAdeNote_1_1Db_1_1NoteDbContext.html", "classAdeNote_1_1Db_1_1NoteDbContext" ]
      ] ],
      [ "Infrastructure", "namespaceAdeNote_1_1Infrastructure.html", [
        [ "Extension", "namespaceAdeNote_1_1Infrastructure_1_1Extension.html", [
          [ "EnumExtensions", "classAdeNote_1_1Infrastructure_1_1Extension_1_1EnumExtensions.html", "classAdeNote_1_1Infrastructure_1_1Extension_1_1EnumExtensions" ],
          [ "MappingService", "classAdeNote_1_1Infrastructure_1_1Extension_1_1MappingService.html", "classAdeNote_1_1Infrastructure_1_1Extension_1_1MappingService" ],
          [ "ResultExtension", "classAdeNote_1_1Infrastructure_1_1Extension_1_1ResultExtension.html", "classAdeNote_1_1Infrastructure_1_1Extension_1_1ResultExtension" ],
          [ "SwaggerOptions", "classAdeNote_1_1Infrastructure_1_1Extension_1_1SwaggerOptions.html", "classAdeNote_1_1Infrastructure_1_1Extension_1_1SwaggerOptions" ],
          [ "ValidatorResult", "classAdeNote_1_1Infrastructure_1_1Extension_1_1ValidatorResult.html", "classAdeNote_1_1Infrastructure_1_1Extension_1_1ValidatorResult" ]
        ] ],
        [ "Repository", "namespaceAdeNote_1_1Infrastructure_1_1Repository.html", [
          [ "BookRepository", "classAdeNote_1_1Infrastructure_1_1Repository_1_1BookRepository.html", "classAdeNote_1_1Infrastructure_1_1Repository_1_1BookRepository" ],
          [ "HangfireUserRepository", "classAdeNote_1_1Infrastructure_1_1Repository_1_1HangfireUserRepository.html", "classAdeNote_1_1Infrastructure_1_1Repository_1_1HangfireUserRepository" ],
          [ "IBookRepository", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IBookRepository.html", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IBookRepository" ],
          [ "IHangfireUserRepository", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IHangfireUserRepository.html", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IHangfireUserRepository" ],
          [ "ILabelPageRepository", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelPageRepository.html", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelPageRepository" ],
          [ "ILabelRepository", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelRepository.html", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ILabelRepository" ],
          [ "IPageRepository", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IPageRepository.html", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IPageRepository" ],
          [ "IRecoveryCodeRepository", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRecoveryCodeRepository.html", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRecoveryCodeRepository" ],
          [ "IRefreshTokenRepository", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRefreshTokenRepository.html", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRefreshTokenRepository" ],
          [ "IRepository", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository.html", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IRepository" ],
          [ "ITicketRepository", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ITicketRepository.html", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1ITicketRepository" ],
          [ "IUserRepository", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IUserRepository.html", "interfaceAdeNote_1_1Infrastructure_1_1Repository_1_1IUserRepository" ],
          [ "LabelPageRepository", "classAdeNote_1_1Infrastructure_1_1Repository_1_1LabelPageRepository.html", "classAdeNote_1_1Infrastructure_1_1Repository_1_1LabelPageRepository" ],
          [ "LabelRepository", "classAdeNote_1_1Infrastructure_1_1Repository_1_1LabelRepository.html", "classAdeNote_1_1Infrastructure_1_1Repository_1_1LabelRepository" ],
          [ "PageRepository", "classAdeNote_1_1Infrastructure_1_1Repository_1_1PageRepository.html", "classAdeNote_1_1Infrastructure_1_1Repository_1_1PageRepository" ],
          [ "RecoveryCodeRepository", "classAdeNote_1_1Infrastructure_1_1Repository_1_1RecoveryCodeRepository.html", "classAdeNote_1_1Infrastructure_1_1Repository_1_1RecoveryCodeRepository" ],
          [ "RefreshRepository", "classAdeNote_1_1Infrastructure_1_1Repository_1_1RefreshRepository.html", "classAdeNote_1_1Infrastructure_1_1Repository_1_1RefreshRepository" ],
          [ "Repository", "classAdeNote_1_1Infrastructure_1_1Repository_1_1Repository.html", "classAdeNote_1_1Infrastructure_1_1Repository_1_1Repository" ],
          [ "TicketRepository", "classAdeNote_1_1Infrastructure_1_1Repository_1_1TicketRepository.html", "classAdeNote_1_1Infrastructure_1_1Repository_1_1TicketRepository" ],
          [ "UserRepository", "classAdeNote_1_1Infrastructure_1_1Repository_1_1UserRepository.html", "classAdeNote_1_1Infrastructure_1_1Repository_1_1UserRepository" ]
        ] ],
        [ "Services", "namespaceAdeNote_1_1Infrastructure_1_1Services.html", [
          [ "AuthService", "classAdeNote_1_1Infrastructure_1_1Services_1_1AuthService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1AuthService" ],
          [ "BlobService", "classAdeNote_1_1Infrastructure_1_1Services_1_1BlobService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1BlobService" ],
          [ "BookService", "classAdeNote_1_1Infrastructure_1_1Services_1_1BookService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1BookService" ],
          [ "EmailService", "classAdeNote_1_1Infrastructure_1_1Services_1_1EmailService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1EmailService" ],
          [ "ExcelService", "classAdeNote_1_1Infrastructure_1_1Services_1_1ExcelService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1ExcelService" ],
          [ "ExportService", "classAdeNote_1_1Infrastructure_1_1Services_1_1ExportService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1ExportService" ],
          [ "FileService", "classAdeNote_1_1Infrastructure_1_1Services_1_1FileService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1FileService" ],
          [ "IAuthService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IAuthService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IAuthService" ],
          [ "IBlobService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IBlobService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IBlobService" ],
          [ "IBookService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IBookService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IBookService" ],
          [ "IEmailService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IEmailService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IEmailService" ],
          [ "IExcel", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IExcel.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IExcel" ],
          [ "IExportService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IExportService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IExportService" ],
          [ "IFileService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IFileService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IFileService" ],
          [ "ILabelService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ILabelService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ILabelService" ],
          [ "INotificationService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1INotificationService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1INotificationService" ],
          [ "IPageService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IPageService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IPageService" ],
          [ "ISmsService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ISmsService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ISmsService" ],
          [ "IStatisticsService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IStatisticsService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IStatisticsService" ],
          [ "ITextTranslation", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ITextTranslation.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ITextTranslation" ],
          [ "ITicketService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ITicketService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1ITicketService" ],
          [ "IUserService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IUserService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IUserService" ],
          [ "IValidatorService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IValidatorService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IValidatorService" ],
          [ "IWordService", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IWordService.html", "interfaceAdeNote_1_1Infrastructure_1_1Services_1_1IWordService" ],
          [ "LabelService", "classAdeNote_1_1Infrastructure_1_1Services_1_1LabelService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1LabelService" ],
          [ "NotificationService", "classAdeNote_1_1Infrastructure_1_1Services_1_1NotificationService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1NotificationService" ],
          [ "PageService", "classAdeNote_1_1Infrastructure_1_1Services_1_1PageService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1PageService" ],
          [ "SmsService", "classAdeNote_1_1Infrastructure_1_1Services_1_1SmsService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1SmsService" ],
          [ "StatisticService", "classAdeNote_1_1Infrastructure_1_1Services_1_1StatisticService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1StatisticService" ],
          [ "TextTranslation", "classAdeNote_1_1Infrastructure_1_1Services_1_1TextTranslation.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1TextTranslation" ],
          [ "TicketService", "classAdeNote_1_1Infrastructure_1_1Services_1_1TicketService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1TicketService" ],
          [ "UserService", "classAdeNote_1_1Infrastructure_1_1Services_1_1UserService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1UserService" ],
          [ "WordService", "classAdeNote_1_1Infrastructure_1_1Services_1_1WordService.html", "classAdeNote_1_1Infrastructure_1_1Services_1_1WordService" ]
        ] ],
        [ "Utilities", "namespaceAdeNote_1_1Infrastructure_1_1Utilities.html", [
          [ "AI", "namespaceAdeNote_1_1Infrastructure_1_1Utilities_1_1AI.html", [
            [ "Language", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AI_1_1Language.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AI_1_1Language" ],
            [ "TranslateConfiguration", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AI_1_1TranslateConfiguration.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AI_1_1TranslateConfiguration" ]
          ] ],
          [ "HealthChecks", "namespaceAdeNote_1_1Infrastructure_1_1Utilities_1_1HealthChecks.html", [
            [ "APIHealthCheck", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1HealthChecks_1_1APIHealthCheck.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1HealthChecks_1_1APIHealthCheck" ],
            [ "DatabaseHealthCheck", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1HealthChecks_1_1DatabaseHealthCheck.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1HealthChecks_1_1DatabaseHealthCheck" ]
          ] ],
          [ "ValidationAttributes", "namespaceAdeNote_1_1Infrastructure_1_1Utilities_1_1ValidationAttributes.html", [
            [ "ExpectedAttribute", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ValidationAttributes_1_1ExpectedAttribute.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ValidationAttributes_1_1ExpectedAttribute" ],
            [ "PasswordAttribute", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ValidationAttributes_1_1PasswordAttribute.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ValidationAttributes_1_1PasswordAttribute" ]
          ] ],
          [ "ActionResult", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ActionResult.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ActionResult" ],
          [ "ActionTokenResult", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ActionTokenResult.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ActionTokenResult" ],
          [ "PaginatedResponse", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1PaginatedResponse.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1PaginatedResponse" ],
          [ "BlobConfiguration", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1BlobConfiguration.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1BlobConfiguration" ],
          [ "DashboardAuthenticationFilter", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1DashboardAuthenticationFilter.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1DashboardAuthenticationFilter" ],
          [ "DatabaseExtension", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1DatabaseExtension.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1DatabaseExtension" ],
          [ "DefaultConfiguration", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1DefaultConfiguration.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1DefaultConfiguration" ],
          [ "Email", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1Email.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1Email" ],
          [ "EmailConfiguration", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1EmailConfiguration.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1EmailConfiguration" ],
          [ "EntityDoc", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1EntityDoc.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1EntityDoc" ],
          [ "ExportEntity", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ExportEntity.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ExportEntity" ],
          [ "HangFireUserConfiguration", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1HangFireUserConfiguration.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1HangFireUserConfiguration" ],
          [ "ImportSheet", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ImportSheet.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ImportSheet" ],
          [ "IUserIdentity", "interfaceAdeNote_1_1Infrastructure_1_1Utilities_1_1IUserIdentity.html", "interfaceAdeNote_1_1Infrastructure_1_1Utilities_1_1IUserIdentity" ],
          [ "RoleRequirement", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1RoleRequirement.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1RoleRequirement" ],
          [ "RoleRequirementHandler", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1RoleRequirementHandler.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1RoleRequirementHandler" ],
          [ "Sms", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1Sms.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1Sms" ],
          [ "SmsConfiguration", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1SmsConfiguration.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1SmsConfiguration" ],
          [ "UserId", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1UserId.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1UserId" ],
          [ "UserIdConverter", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1UserIdConverter.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1UserIdConverter" ],
          [ "UserIdentity", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1UserIdentity.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1UserIdentity" ]
        ] ]
      ] ],
      [ "Migrations", "namespaceAdeNote_1_1Migrations.html", [
        [ "firstmigration", "classAdeNote_1_1Migrations_1_1firstmigration.html", "classAdeNote_1_1Migrations_1_1firstmigration" ],
        [ "secondmigration", "classAdeNote_1_1Migrations_1_1secondmigration.html", "classAdeNote_1_1Migrations_1_1secondmigration" ],
        [ "setuptexttranslation", "classAdeNote_1_1Migrations_1_1setuptexttranslation.html", "classAdeNote_1_1Migrations_1_1setuptexttranslation" ],
        [ "addsalt", "classAdeNote_1_1Migrations_1_1addsalt.html", "classAdeNote_1_1Migrations_1_1addsalt" ],
        [ "saltoptional", "classAdeNote_1_1Migrations_1_1saltoptional.html", "classAdeNote_1_1Migrations_1_1saltoptional" ],
        [ "addrole", "classAdeNote_1_1Migrations_1_1addrole.html", "classAdeNote_1_1Migrations_1_1addrole" ],
        [ "addrecoverycodes", "classAdeNote_1_1Migrations_1_1addrecoverycodes.html", "classAdeNote_1_1Migrations_1_1addrecoverycodes" ],
        [ "addticket", "classAdeNote_1_1Migrations_1_1addticket.html", "classAdeNote_1_1Migrations_1_1addticket" ],
        [ "addissue", "classAdeNote_1_1Migrations_1_1addissue.html", "classAdeNote_1_1Migrations_1_1addissue" ],
        [ "addrecoverycode", "classAdeNote_1_1Migrations_1_1addrecoverycode.html", "classAdeNote_1_1Migrations_1_1addrecoverycode" ],
        [ "descriptionnullable", "classAdeNote_1_1Migrations_1_1descriptionnullable.html", "classAdeNote_1_1Migrations_1_1descriptionnullable" ],
        [ "NoteDbContextModelSnapshot", "classAdeNote_1_1Migrations_1_1NoteDbContextModelSnapshot.html", "classAdeNote_1_1Migrations_1_1NoteDbContextModelSnapshot" ]
      ] ],
      [ "Models", "namespaceAdeNote_1_1Models.html", [
        [ "DTOs", "namespaceAdeNote_1_1Models_1_1DTOs.html", [
          [ "AuthenticatorDTO", "classAdeNote_1_1Models_1_1DTOs_1_1AuthenticatorDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1AuthenticatorDTO" ],
          [ "BookCreateDTO", "classAdeNote_1_1Models_1_1DTOs_1_1BookCreateDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1BookCreateDTO" ],
          [ "BookDTO", "classAdeNote_1_1Models_1_1DTOs_1_1BookDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1BookDTO" ],
          [ "BookPages", "classAdeNote_1_1Models_1_1DTOs_1_1BookPages.html", "classAdeNote_1_1Models_1_1DTOs_1_1BookPages" ],
          [ "BookUpdateDTO", "classAdeNote_1_1Models_1_1DTOs_1_1BookUpdateDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1BookUpdateDTO" ],
          [ "ChangePasswordDTO", "classAdeNote_1_1Models_1_1DTOs_1_1ChangePasswordDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1ChangePasswordDTO" ],
          [ "CreateNoteDTO", "classAdeNote_1_1Models_1_1DTOs_1_1CreateNoteDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1CreateNoteDTO" ],
          [ "CreateUserDTO", "classAdeNote_1_1Models_1_1DTOs_1_1CreateUserDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1CreateUserDTO" ],
          [ "DetailsDTO", "classAdeNote_1_1Models_1_1DTOs_1_1DetailsDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1DetailsDTO" ],
          [ "ImportBookDto", "classAdeNote_1_1Models_1_1DTOs_1_1ImportBookDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1ImportBookDto" ],
          [ "LabelCreateDTO", "classAdeNote_1_1Models_1_1DTOs_1_1LabelCreateDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1LabelCreateDTO" ],
          [ "LabelDTO", "classAdeNote_1_1Models_1_1DTOs_1_1LabelDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1LabelDTO" ],
          [ "LabelUpdateDTO", "classAdeNote_1_1Models_1_1DTOs_1_1LabelUpdateDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1LabelUpdateDTO" ],
          [ "LoginDTO", "classAdeNote_1_1Models_1_1DTOs_1_1LoginDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1LoginDTO" ],
          [ "PageCreateDTO", "classAdeNote_1_1Models_1_1DTOs_1_1PageCreateDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1PageCreateDTO" ],
          [ "PageDTO", "classAdeNote_1_1Models_1_1DTOs_1_1PageDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1PageDTO" ],
          [ "PageUpdateDTO", "classAdeNote_1_1Models_1_1DTOs_1_1PageUpdateDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1PageUpdateDTO" ],
          [ "StatisticsDto", "classAdeNote_1_1Models_1_1DTOs_1_1StatisticsDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1StatisticsDto" ],
          [ "TicketCreateDto", "classAdeNote_1_1Models_1_1DTOs_1_1TicketCreateDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1TicketCreateDto" ],
          [ "TicketDTO", "classAdeNote_1_1Models_1_1DTOs_1_1TicketDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1TicketDTO" ],
          [ "TicketsDTO", "classAdeNote_1_1Models_1_1DTOs_1_1TicketsDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1TicketsDTO" ],
          [ "TicketStatusDto", "classAdeNote_1_1Models_1_1DTOs_1_1TicketStatusDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1TicketStatusDto" ],
          [ "TicketStreamDto", "classAdeNote_1_1Models_1_1DTOs_1_1TicketStreamDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1TicketStreamDto" ],
          [ "TranslationDto", "classAdeNote_1_1Models_1_1DTOs_1_1TranslationDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1TranslationDto" ],
          [ "UserDTO", "classAdeNote_1_1Models_1_1DTOs_1_1UserDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1UserDTO" ]
        ] ],
        [ "BaseClass", "classAdeNote_1_1Models_1_1BaseClass.html", "classAdeNote_1_1Models_1_1BaseClass" ],
        [ "Book", "classAdeNote_1_1Models_1_1Book.html", "classAdeNote_1_1Models_1_1Book" ],
        [ "HangfireUser", "classAdeNote_1_1Models_1_1HangfireUser.html", "classAdeNote_1_1Models_1_1HangfireUser" ],
        [ "BaseEntity", "classAdeNote_1_1Models_1_1BaseEntity.html", "classAdeNote_1_1Models_1_1BaseEntity" ],
        [ "Label", "classAdeNote_1_1Models_1_1Label.html", "classAdeNote_1_1Models_1_1Label" ],
        [ "LabelPage", "classAdeNote_1_1Models_1_1LabelPage.html", "classAdeNote_1_1Models_1_1LabelPage" ],
        [ "Page", "classAdeNote_1_1Models_1_1Page.html", "classAdeNote_1_1Models_1_1Page" ],
        [ "RecoveryCode", "classAdeNote_1_1Models_1_1RecoveryCode.html", "classAdeNote_1_1Models_1_1RecoveryCode" ],
        [ "RefreshToken", "classAdeNote_1_1Models_1_1RefreshToken.html", "classAdeNote_1_1Models_1_1RefreshToken" ],
        [ "Ticket", "classAdeNote_1_1Models_1_1Ticket.html", "classAdeNote_1_1Models_1_1Ticket" ],
        [ "User", "classAdeNote_1_1Models_1_1User.html", "classAdeNote_1_1Models_1_1User" ]
      ] ]
    ] ]
];