var DashboardAuthenticationFilter_8cs =
[
    [ "AdeNote.Infrastructure.Utilities.AuthenticationFilter.DashboardAuthenticationFilter", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthenticationFilter_1_1DashboardAuthenticationFilter.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthenticationFilter_1_1DashboardAuthenticationFilter" ]
];