var dir_acc1230cf0f6a94710e2054215a050f1 =
[
    [ "CreateBooksValidator.cs", "CreateBooksValidator_8cs.html", "CreateBooksValidator_8cs" ],
    [ "CreateBookValidator.cs", "CreateBookValidator_8cs.html", "CreateBookValidator_8cs" ],
    [ "CreatePageLabelsValidator.cs", "CreatePageLabelsValidator_8cs.html", "CreatePageLabelsValidator_8cs" ],
    [ "CreatePageValidator.cs", "CreatePageValidator_8cs.html", "CreatePageValidator_8cs" ],
    [ "CreateTicketValidator.cs", "CreateTicketValidator_8cs.html", "CreateTicketValidator_8cs" ],
    [ "FetchAllTicketValidator.cs", "FetchAllTicketValidator_8cs.html", "FetchAllTicketValidator_8cs" ],
    [ "FetchTicketByIdValidator.cs", "FetchTicketByIdValidator_8cs.html", "FetchTicketByIdValidator_8cs" ],
    [ "FetchTicketsByNameValidator.cs", "FetchTicketsByNameValidator_8cs.html", "FetchTicketsByNameValidator_8cs" ],
    [ "FetchUserTicketByIdValidator.cs", "FetchUserTicketByIdValidator_8cs.html", "FetchUserTicketByIdValidator_8cs" ],
    [ "GetAllBooksValidator.cs", "GetAllBooksValidator_8cs.html", "GetAllBooksValidator_8cs" ],
    [ "GetAllLabelsValidator.cs", "GetAllLabelsValidator_8cs.html", "GetAllLabelsValidator_8cs" ],
    [ "GetAllPagesValidator.cs", "GetAllPagesValidator_8cs.html", "GetAllPagesValidator_8cs" ],
    [ "GetBookByIdValidator.cs", "GetBookByIdValidator_8cs.html", "GetBookByIdValidator_8cs" ],
    [ "GetPageByIdValidator.cs", "GetPageByIdValidator_8cs.html", "GetPageByIdValidator_8cs" ],
    [ "InsertVideoValidator.cs", "InsertVideoValidator_8cs.html", "InsertVideoValidator_8cs" ],
    [ "RemoveAllPageLabelsValidator.cs", "RemoveAllPageLabelsValidator_8cs.html", "RemoveAllPageLabelsValidator_8cs" ],
    [ "RemoveBookValidator.cs", "RemoveBookValidator_8cs.html", "RemoveBookValidator_8cs" ],
    [ "RemovePageLabelValidator.cs", "RemovePageLabelValidator_8cs.html", "RemovePageLabelValidator_8cs" ],
    [ "RemovePageValidator.cs", "RemovePageValidator_8cs.html", "RemovePageValidator_8cs" ],
    [ "SearchTicketsByDateValidator.cs", "SearchTicketsByDateValidator_8cs.html", "SearchTicketsByDateValidator_8cs" ],
    [ "SearchTicketsValidator.cs", "SearchTicketsValidator_8cs.html", "SearchTicketsValidator_8cs" ],
    [ "TranslatePageValidator.cs", "TranslatePageValidator_8cs.html", "TranslatePageValidator_8cs" ],
    [ "UpdateBookValidator.cs", "UpdateBookValidator_8cs.html", "UpdateBookValidator_8cs" ],
    [ "UpdateLabelValidator.cs", "UpdateLabelValidator_8cs.html", "UpdateLabelValidator_8cs" ],
    [ "UpdatePageValidator.cs", "UpdatePageValidator_8cs.html", "UpdatePageValidator_8cs" ],
    [ "UpdateTicketValidator.cs", "UpdateTicketValidator_8cs.html", "UpdateTicketValidator_8cs" ]
];