var MiniProfilerAuthorization_8cs =
[
    [ "AdeNote.Infrastructure.Utilities.AuthenticationFilter.MiniProfilerAuthorization", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthenticationFilter_1_1MiniProfilerAuthorization.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthenticationFilter_1_1MiniProfilerAuthorization" ]
];