var namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetBookdById =
[
    [ "GetBookByIdRequest", "classAdeNote_1_1Infrastructure_1_1Requests_1_1GetBookdById_1_1GetBookByIdRequest.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1GetBookdById_1_1GetBookByIdRequest" ],
    [ "GetBookByIdRequestHandler", "classAdeNote_1_1Infrastructure_1_1Requests_1_1GetBookdById_1_1GetBookByIdRequestHandler.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1GetBookdById_1_1GetBookByIdRequestHandler" ]
];