var namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1SearchTickets =
[
    [ "SearchTicketsRequest", "classAdeNote_1_1Infrastructure_1_1Requests_1_1SearchTickets_1_1SearchTicketsRequest.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1SearchTickets_1_1SearchTicketsRequest" ],
    [ "SearchTicketsRequestHandler", "classAdeNote_1_1Infrastructure_1_1Requests_1_1SearchTickets_1_1SearchTicketsRequestHandler.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1SearchTickets_1_1SearchTicketsRequestHandler" ]
];