var namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1UpdateLabel =
[
    [ "UpdateLabelRequest", "classAdeNote_1_1Infrastructure_1_1Requests_1_1UpdateLabel_1_1UpdateLabelRequest.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1UpdateLabel_1_1UpdateLabelRequest" ],
    [ "UpdateLabelRequestHandler", "classAdeNote_1_1Infrastructure_1_1Requests_1_1UpdateLabel_1_1UpdateLabelRequestHandler.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1UpdateLabel_1_1UpdateLabelRequestHandler" ]
];