var namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveTicket =
[
    [ "RemoveTicketRequest", "classAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveTicket_1_1RemoveTicketRequest.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveTicket_1_1RemoveTicketRequest" ],
    [ "RemoveTicketRequestHandler", "classAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveTicket_1_1RemoveTicketRequestHandler.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveTicket_1_1RemoveTicketRequestHandler" ]
];