var namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetPagesById =
[
    [ "GetPageByIdRequest", "classAdeNote_1_1Infrastructure_1_1Requests_1_1GetPagesById_1_1GetPageByIdRequest.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1GetPagesById_1_1GetPageByIdRequest" ],
    [ "GetPageByIdRequestHandler", "classAdeNote_1_1Infrastructure_1_1Requests_1_1GetPagesById_1_1GetPageByIdRequestHandler.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1GetPagesById_1_1GetPageByIdRequestHandler" ]
];