var namespaceAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthenticationFilter =
[
    [ "DashboardAuthenticationFilter", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthenticationFilter_1_1DashboardAuthenticationFilter.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthenticationFilter_1_1DashboardAuthenticationFilter" ],
    [ "MiniProfilerAuthorization", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthenticationFilter_1_1MiniProfilerAuthorization.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthenticationFilter_1_1MiniProfilerAuthorization" ],
    [ "UserConfiguration", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthenticationFilter_1_1UserConfiguration.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthenticationFilter_1_1UserConfiguration" ]
];