var namespaceAdeNote_1_1Models_1_1DTOs =
[
    [ "AuthenticatorDTO", "classAdeNote_1_1Models_1_1DTOs_1_1AuthenticatorDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1AuthenticatorDTO" ],
    [ "BookCreateDTO", "classAdeNote_1_1Models_1_1DTOs_1_1BookCreateDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1BookCreateDTO" ],
    [ "BookDTO", "classAdeNote_1_1Models_1_1DTOs_1_1BookDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1BookDTO" ],
    [ "BookPages", "classAdeNote_1_1Models_1_1DTOs_1_1BookPages.html", "classAdeNote_1_1Models_1_1DTOs_1_1BookPages" ],
    [ "BookUpdateDTO", "classAdeNote_1_1Models_1_1DTOs_1_1BookUpdateDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1BookUpdateDTO" ],
    [ "ChangePasswordDTO", "classAdeNote_1_1Models_1_1DTOs_1_1ChangePasswordDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1ChangePasswordDTO" ],
    [ "CreateNoteDTO", "classAdeNote_1_1Models_1_1DTOs_1_1CreateNoteDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1CreateNoteDTO" ],
    [ "CreateThreadDto", "classAdeNote_1_1Models_1_1DTOs_1_1CreateThreadDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1CreateThreadDto" ],
    [ "CreateUserDTO", "classAdeNote_1_1Models_1_1DTOs_1_1CreateUserDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1CreateUserDTO" ],
    [ "DetailsDTO", "classAdeNote_1_1Models_1_1DTOs_1_1DetailsDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1DetailsDTO" ],
    [ "ImportBookDto", "classAdeNote_1_1Models_1_1DTOs_1_1ImportBookDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1ImportBookDto" ],
    [ "InsertVideoDto", "classAdeNote_1_1Models_1_1DTOs_1_1InsertVideoDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1InsertVideoDto" ],
    [ "LabelCreateDTO", "classAdeNote_1_1Models_1_1DTOs_1_1LabelCreateDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1LabelCreateDTO" ],
    [ "LabelDTO", "classAdeNote_1_1Models_1_1DTOs_1_1LabelDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1LabelDTO" ],
    [ "LabelUpdateDTO", "classAdeNote_1_1Models_1_1DTOs_1_1LabelUpdateDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1LabelUpdateDTO" ],
    [ "LoginDTO", "classAdeNote_1_1Models_1_1DTOs_1_1LoginDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1LoginDTO" ],
    [ "PageCreateDTO", "classAdeNote_1_1Models_1_1DTOs_1_1PageCreateDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1PageCreateDTO" ],
    [ "PageDTO", "classAdeNote_1_1Models_1_1DTOs_1_1PageDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1PageDTO" ],
    [ "PageUpdateDTO", "classAdeNote_1_1Models_1_1DTOs_1_1PageUpdateDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1PageUpdateDTO" ],
    [ "SolvedTicketDto", "classAdeNote_1_1Models_1_1DTOs_1_1SolvedTicketDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1SolvedTicketDto" ],
    [ "StatisticsDto", "classAdeNote_1_1Models_1_1DTOs_1_1StatisticsDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1StatisticsDto" ],
    [ "SubThreadDto", "classAdeNote_1_1Models_1_1DTOs_1_1SubThreadDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1SubThreadDto" ],
    [ "TicketCreateDto", "classAdeNote_1_1Models_1_1DTOs_1_1TicketCreateDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1TicketCreateDto" ],
    [ "TicketDTO", "classAdeNote_1_1Models_1_1DTOs_1_1TicketDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1TicketDTO" ],
    [ "TicketsDTO", "classAdeNote_1_1Models_1_1DTOs_1_1TicketsDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1TicketsDTO" ],
    [ "TicketStatusDto", "classAdeNote_1_1Models_1_1DTOs_1_1TicketStatusDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1TicketStatusDto" ],
    [ "TicketStreamDto", "classAdeNote_1_1Models_1_1DTOs_1_1TicketStreamDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1TicketStreamDto" ],
    [ "TranslationDto", "classAdeNote_1_1Models_1_1DTOs_1_1TranslationDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1TranslationDto" ],
    [ "TweetThreadDto", "classAdeNote_1_1Models_1_1DTOs_1_1TweetThreadDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1TweetThreadDto" ],
    [ "TweetThreadDtos", "classAdeNote_1_1Models_1_1DTOs_1_1TweetThreadDtos.html", "classAdeNote_1_1Models_1_1DTOs_1_1TweetThreadDtos" ],
    [ "UpdateThreadDto", "classAdeNote_1_1Models_1_1DTOs_1_1UpdateThreadDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1UpdateThreadDto" ],
    [ "UserDTO", "classAdeNote_1_1Models_1_1DTOs_1_1UserDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1UserDTO" ],
    [ "UsersDTO", "classAdeNote_1_1Models_1_1DTOs_1_1UsersDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1UsersDTO" ],
    [ "UserTicketDto", "classAdeNote_1_1Models_1_1DTOs_1_1UserTicketDto.html", "classAdeNote_1_1Models_1_1DTOs_1_1UserTicketDto" ],
    [ "VideoDTO", "classAdeNote_1_1Models_1_1DTOs_1_1VideoDTO.html", "classAdeNote_1_1Models_1_1DTOs_1_1VideoDTO" ]
];