var namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetAllBooks =
[
    [ "GetAllBooksRequest", "classAdeNote_1_1Infrastructure_1_1Requests_1_1GetAllBooks_1_1GetAllBooksRequest.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1GetAllBooks_1_1GetAllBooksRequest" ],
    [ "GetAllBooksRequestHandler", "classAdeNote_1_1Infrastructure_1_1Requests_1_1GetAllBooks_1_1GetAllBooksRequestHandler.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1GetAllBooks_1_1GetAllBooksRequestHandler" ]
];