var namespaceAdeNote_1_1Infrastructure_1_1Requests =
[
    [ "CreateBook", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreateBook.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreateBook" ],
    [ "CreateBooks", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreateBooks.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreateBooks" ],
    [ "CreateLabel", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreateLabel.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreateLabel" ],
    [ "CreatePage", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreatePage.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreatePage" ],
    [ "CreatePageLabels", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreatePageLabels.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreatePageLabels" ],
    [ "CreateTicket", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreateTicket.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreateTicket" ],
    [ "FetchAllTickets", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1FetchAllTickets.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1FetchAllTickets" ],
    [ "FetchAllTicketsByName", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1FetchAllTicketsByName.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1FetchAllTicketsByName" ],
    [ "FetchTicketById", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1FetchTicketById.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1FetchTicketById" ],
    [ "FetchUserTicketById", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1FetchUserTicketById.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1FetchUserTicketById" ],
    [ "GetAllBooks", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetAllBooks.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetAllBooks" ],
    [ "GetAllLabels", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetAllLabels.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetAllLabels" ],
    [ "GetAllPages", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetAllPages.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetAllPages" ],
    [ "GetBookdById", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetBookdById.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetBookdById" ],
    [ "GetLabelById", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetLabelById.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetLabelById" ],
    [ "GetPagesById", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetPagesById.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1GetPagesById" ],
    [ "RemoveAllPageLabels", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveAllPageLabels.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveAllPageLabels" ],
    [ "RemoveBook", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveBook.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveBook" ],
    [ "RemoveLabel", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveLabel.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveLabel" ],
    [ "RemovePage", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemovePage.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemovePage" ],
    [ "RemovePageLabel", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemovePageLabel.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemovePageLabel" ],
    [ "RemoveTicket", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveTicket.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1RemoveTicket" ],
    [ "SearchTickets", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1SearchTickets.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1SearchTickets" ],
    [ "SearchTicketsByDate", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1SearchTicketsByDate.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1SearchTicketsByDate" ],
    [ "TranslatePage", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1TranslatePage.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1TranslatePage" ],
    [ "UpdateBook", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1UpdateBook.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1UpdateBook" ],
    [ "UpdateLabel", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1UpdateLabel.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1UpdateLabel" ],
    [ "UpdatePage", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1UpdatePage.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1UpdatePage" ],
    [ "UpdateTicket", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1UpdateTicket.html", "namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1UpdateTicket" ]
];