var namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1FetchTicketById =
[
    [ "FetchTicketByIdRequest", "classAdeNote_1_1Infrastructure_1_1Requests_1_1FetchTicketById_1_1FetchTicketByIdRequest.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1FetchTicketById_1_1FetchTicketByIdRequest" ],
    [ "FetchTicketByIdRequestHandler", "classAdeNote_1_1Infrastructure_1_1Requests_1_1FetchTicketById_1_1FetchTicketByIdRequestHandler.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1FetchTicketById_1_1FetchTicketByIdRequestHandler" ]
];