var namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1InsertVideo =
[
    [ "InsertVideoRequest", "classAdeNote_1_1Infrastructure_1_1Requests_1_1InsertVideo_1_1InsertVideoRequest.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1InsertVideo_1_1InsertVideoRequest" ],
    [ "InsertVideoRequestHandler", "classAdeNote_1_1Infrastructure_1_1Requests_1_1InsertVideo_1_1InsertVideoRequestHandler.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1InsertVideo_1_1InsertVideoRequestHandler" ]
];