var namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1CreateTicket =
[
    [ "CreateTicketRequest", "classAdeNote_1_1Infrastructure_1_1Requests_1_1CreateTicket_1_1CreateTicketRequest.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1CreateTicket_1_1CreateTicketRequest" ],
    [ "CreateTicketRequestHandler", "classAdeNote_1_1Infrastructure_1_1Requests_1_1CreateTicket_1_1CreateTicketRequestHandler.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1CreateTicket_1_1CreateTicketRequestHandler" ]
];