var namespaceAdeNote_1_1Infrastructure_1_1Requests_1_1FetchAllTicketsByName =
[
    [ "FetchAllTicketsByNameRequest", "classAdeNote_1_1Infrastructure_1_1Requests_1_1FetchAllTicketsByName_1_1FetchAllTicketsByNameRequest.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1FetchAllTicketsByName_1_1FetchAllTicketsByNameRequest" ],
    [ "FetchAllTicketsByNameRequestHandler", "classAdeNote_1_1Infrastructure_1_1Requests_1_1FetchAllTicketsByName_1_1FetchAllTicketsByNameRequestHandler.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1FetchAllTicketsByName_1_1FetchAllTicketsByNameRequestHandler" ]
];