var RoleRequirementHandler_8cs =
[
    [ "AdeNote.Infrastructure.Utilities.AuthorisationHandler.RoleRequirementHandler", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthorisationHandler_1_1RoleRequirementHandler.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1AuthorisationHandler_1_1RoleRequirementHandler" ]
];