var SearchTicketsByDateRequest_8cs =
[
    [ "AdeNote.Infrastructure.Requests.SearchTicketsByDate.SearchTicketsByDateRequest", "classAdeNote_1_1Infrastructure_1_1Requests_1_1SearchTicketsByDate_1_1SearchTicketsByDateRequest.html", "classAdeNote_1_1Infrastructure_1_1Requests_1_1SearchTicketsByDate_1_1SearchTicketsByDateRequest" ]
];