var ValidDateTimeAttribute_8cs =
[
    [ "AdeNote.Infrastructure.Utilities.ValidationAttributes.ValidDateTimeAttribute", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ValidationAttributes_1_1ValidDateTimeAttribute.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ValidationAttributes_1_1ValidDateTimeAttribute" ]
];