var ValidTicketIdAttribute_8cs =
[
    [ "AdeNote.Infrastructure.Utilities.ValidationAttributes.ValidTicketIdAttribute", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ValidationAttributes_1_1ValidTicketIdAttribute.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ValidationAttributes_1_1ValidTicketIdAttribute" ]
];