var ValidCollectionAttribute_8cs =
[
    [ "AdeNote.Infrastructure.Utilities.ValidationAttributes.ValidCollectionAttribute", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ValidationAttributes_1_1ValidCollectionAttribute.html", "classAdeNote_1_1Infrastructure_1_1Utilities_1_1ValidationAttributes_1_1ValidCollectionAttribute" ]
];